name: fetch

on:
  schedule:
    - cron:  '27 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        lfs: true

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'

    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: |
        npm install
        node perform.js
        node clean.js
        git config --local user.email "you@example.com"
        git config --local user.name "Your Name"
        git config pull.rebase false
        git add ./_posts/*.md
        git commit -m 'update'
        git pull
        git push origin master
